# Generated by Django 4.1.7 on 2023-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('1', 'Activa'), ('0', 'Inactiva')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
