# Generated by Django 4.2.1 on 2023-06-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.CharField(max_length=30, verbose_name='cantidad'),
        ),
    ]
