# Generated by Django 4.2.1 on 2023-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=45, verbose_name='precio')),
                ('cantidad', models.CharField(max_length=45, verbose_name='cantidad')),
                ('valortotal', models.CharField(max_length=45, verbose_name='valor total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'detallecompras',
            },
        ),
    ]
