# Generated by Django 4.2.1 on 2023-06-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_detalle_venta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_venta',
            new_name='Detalleventa',
        ),
    ]
